SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `dechiffrage` (
  `id_dechiffrage` int(11) NOT NULL,
  `pathTxtFichier` varchar(25) DEFAULT NULL,
  `cleDecodage` varchar(25) DEFAULT NULL,
  `tauxDeReussite` double DEFAULT NULL,
  `fristswordfound` text,
  `email` varchar(25) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `dico` (
  `id` int(11) NOT NULL,
  `mot` varchar(25) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=22665 DEFAULT CHARSET=latin1;


ALTER TABLE `dechiffrage`
  ADD PRIMARY KEY (`id_dechiffrage`);

ALTER TABLE `dico`
  ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `mot` (`mot`);


ALTER TABLE `dechiffrage`
  MODIFY `id_dechiffrage` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
ALTER TABLE `dico`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=22665;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
